/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YRouteImport } from './routes/_y'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as YAppRouteImport } from './routes/_y/app'
import { Route as YLegalRouteImport } from './routes/_y/legal'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as YAppChatsRouteImport } from './routes/_y/app.chats'
import { Route as YAppCommunitiesRouteImport } from './routes/_y/app.communities'
import { Route as YAppExploreRouteImport } from './routes/_y/app.explore'
import { Route as YAppHomeRouteImport } from './routes/_y/app.home'
import { Route as YAppLegalRouteImport } from './routes/_y/app.legal'
import { Route as YAppNotificationsRouteImport } from './routes/_y/app.notifications'
import { Route as YAppProfileRouteImport } from './routes/_y/app.profile'
import { Route as YAppReelsRouteImport } from './routes/_y/app.reels'
import { Route as YAppSettingsRouteImport } from './routes/_y/app.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YRoute = YRouteImport.update({
  id: '/_y',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const YAppRoute = YAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => YRoute,
} as any)
const YLegalRoute = YLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => YRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const YAppChatsRoute = YAppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => YAppRoute,
} as any)
const YAppCommunitiesRoute = YAppCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => YAppRoute,
} as any)
const YAppExploreRoute = YAppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => YAppRoute,
} as any)
const YAppHomeRoute = YAppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => YAppRoute,
} as any)
const YAppLegalRoute = YAppLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => YAppRoute,
} as any)
const YAppNotificationsRoute = YAppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => YAppRoute,
} as any)
const YAppProfileRoute = YAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => YAppRoute,
} as any)
const YAppReelsRoute = YAppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => YAppRoute,
} as any)
const YAppSettingsRoute = YAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => YAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof YAppRouteWithChildren
  '/legal': typeof YLegalRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/chats': typeof YAppChatsRoute
  '/app/communities': typeof YAppCommunitiesRoute
  '/app/explore': typeof YAppExploreRoute
  '/app/home': typeof YAppHomeRoute
  '/app/legal': typeof YAppLegalRoute
  '/app/notifications': typeof YAppNotificationsRoute
  '/app/profile': typeof YAppProfileRoute
  '/app/reels': typeof YAppReelsRoute
  '/app/settings': typeof YAppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app': typeof YAppRouteWithChildren
  '/legal': typeof YLegalRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/chats': typeof YAppChatsRoute
  '/app/communities': typeof YAppCommunitiesRoute
  '/app/explore': typeof YAppExploreRoute
  '/app/home': typeof YAppHomeRoute
  '/app/legal': typeof YAppLegalRoute
  '/app/notifications': typeof YAppNotificationsRoute
  '/app/profile': typeof YAppProfileRoute
  '/app/reels': typeof YAppReelsRoute
  '/app/settings': typeof YAppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_y': typeof YRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_y/app': typeof YAppRouteWithChildren
  '/_y/legal': typeof YLegalRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_y/app/chats': typeof YAppChatsRoute
  '/_y/app/communities': typeof YAppCommunitiesRoute
  '/_y/app/explore': typeof YAppExploreRoute
  '/_y/app/home': typeof YAppHomeRoute
  '/_y/app/legal': typeof YAppLegalRoute
  '/_y/app/notifications': typeof YAppNotificationsRoute
  '/_y/app/profile': typeof YAppProfileRoute
  '/_y/app/reels': typeof YAppReelsRoute
  '/_y/app/settings': typeof YAppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/signup'
    | '/app'
    | '/legal'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/app/chats'
    | '/app/communities'
    | '/app/explore'
    | '/app/home'
    | '/app/legal'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reels'
    | '/app/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/signup'
    | '/app'
    | '/legal'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/app/chats'
    | '/app/communities'
    | '/app/explore'
    | '/app/home'
    | '/app/legal'
    | '/app/notifications'
    | '/app/profile'
    | '/app/reels'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/_y'
    | '/callback'
    | '/login'
    | '/signup'
    | '/_y/app'
    | '/_y/legal'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/signup'
    | '/_y/app/chats'
    | '/_y/app/communities'
    | '/_y/app/explore'
    | '/_y/app/home'
    | '/_y/app/legal'
    | '/_y/app/notifications'
    | '/_y/app/profile'
    | '/_y/app/reels'
    | '/_y/app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YRoute: typeof YRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_y': {
      id: '/_y'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof YRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_y/app': {
      id: '/_y/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof YAppRouteImport
      parentRoute: typeof YRoute
    }
    '/_y/legal': {
      id: '/_y/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof YLegalRouteImport
      parentRoute: typeof YRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_y/app/chats': {
      id: '/_y/app/chats'
      path: '/chats'
      fullPath: '/app/chats'
      preLoaderRoute: typeof YAppChatsRouteImport
      parentRoute: typeof YAppRoute
    }
    '/_y/app/communities': {
      id: '/_y/app/communities'
      path: '/communities'
      fullPath: '/app/communities'
      preLoaderRoute: typeof YAppCommunitiesRouteImport
      parentRoute: typeof YAppRoute
    }
    '/_y/app/explore': {
      id: '/_y/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof YAppExploreRouteImport
      parentRoute: typeof YAppRoute
    }
    '/_y/app/home': {
      id: '/_y/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof YAppHomeRouteImport
      parentRoute: typeof YAppRoute
    }
    '/_y/app/legal': {
      id: '/_y/app/legal'
      path: '/legal'
      fullPath: '/app/legal'
      preLoaderRoute: typeof YAppLegalRouteImport
      parentRoute: typeof YAppRoute
    }
    '/_y/app/notifications': {
      id: '/_y/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof YAppNotificationsRouteImport
      parentRoute: typeof YAppRoute
    }
    '/_y/app/profile': {
      id: '/_y/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof YAppProfileRouteImport
      parentRoute: typeof YAppRoute
    }
    '/_y/app/reels': {
      id: '/_y/app/reels'
      path: '/reels'
      fullPath: '/app/reels'
      preLoaderRoute: typeof YAppReelsRouteImport
      parentRoute: typeof YAppRoute
    }
    '/_y/app/settings': {
      id: '/_y/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof YAppSettingsRouteImport
      parentRoute: typeof YAppRoute
    }
  }
}

interface YAppRouteChildren {
  YAppChatsRoute: typeof YAppChatsRoute
  YAppCommunitiesRoute: typeof YAppCommunitiesRoute
  YAppExploreRoute: typeof YAppExploreRoute
  YAppHomeRoute: typeof YAppHomeRoute
  YAppLegalRoute: typeof YAppLegalRoute
  YAppNotificationsRoute: typeof YAppNotificationsRoute
  YAppProfileRoute: typeof YAppProfileRoute
  YAppReelsRoute: typeof YAppReelsRoute
  YAppSettingsRoute: typeof YAppSettingsRoute
}

const YAppRouteChildren: YAppRouteChildren = {
  YAppChatsRoute: YAppChatsRoute,
  YAppCommunitiesRoute: YAppCommunitiesRoute,
  YAppExploreRoute: YAppExploreRoute,
  YAppHomeRoute: YAppHomeRoute,
  YAppLegalRoute: YAppLegalRoute,
  YAppNotificationsRoute: YAppNotificationsRoute,
  YAppProfileRoute: YAppProfileRoute,
  YAppReelsRoute: YAppReelsRoute,
  YAppSettingsRoute: YAppSettingsRoute,
}

const YAppRouteWithChildren = YAppRoute._addFileChildren(YAppRouteChildren)

interface YRouteChildren {
  YAppRoute: typeof YAppRouteWithChildren
  YLegalRoute: typeof YLegalRoute
}

const YRouteChildren: YRouteChildren = {
  YAppRoute: YAppRouteWithChildren,
  YLegalRoute: YLegalRoute,
}

const YRouteWithChildren = YRoute._addFileChildren(YRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YRoute: YRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
